# angularやsanitize.cssのモジュールをアップグレードしたい方へ(仮)
# 1. npmでモジュールを ホームディレクトリ上に アップデートする
# 2. ホームディレクトリに node_modules ディレクトリからモジュールファイルを持っていく
# 3. angularは static/js/ に、sanitize.cssは themes/aokashi_base/static/css にコピー

title = "Aokashi Home"
baseURL = "https://www.aokashi.net/"
theme = "aokashi_base"
defaultLayout = "information"
languageCode = "ja"
defaultContentLanguage = "ja"
Copyright = "Copyright © 2010-2017 Aokashi."
hasCJKLanguage = true
uglyURLs = true
plualizeListTitles = false

[[menu.main]]
  name = "WWA"
  weight = 1
  identifier = "wwa"
  url = "/wwa/"
  # WWAは OneDrive/Documents/Games/WWA -> wwa/
[[menu.main]]
  name = "作品"
  weight = 2
  identifier = "works"
  url = "/works/"
[[menu.main]]
  name = "素材"
  weight = 3
  identifier = "materials"
  url = "/materials/"
  # WWA素材は OneDrive/Pictures/WWAMaterials/Public -> materials/wwa/
  # アイコン素材は Dropbox/Pictures/Web/Icons -> materials/icon/
[[menu.main]]
  name = "資料"
  weight = 4
  identifier = "docs"
  url = "https://contents.aokashi.net/docs/"
[[menu.main]]
  name = "Aokashiについて"
  weight = 5
  identifier = "aboutme"
  url = "/aboutme/"

[[menu.footer]]
  name = "お知らせ"
  weight = 1
  identifier = "informations"
  url = "/informations.html"
[[menu.footer]]
  name = "当サイトについて"
  weight = 2
  identifier = "about"
  url = "/about.html"
[[menu.footer]]
  name = "WWA FanSquare"
  weight = 3
  identifier = "wwafansq"
  url = "http://www.wwafansq.com"

[params]
  blog = "http://aokashi.hatenablog.jp"
  twitter = "https://twitter.com/aokashi"
  github = "https://github.com/aokashi"
